29/06/2017 19:18:26 ==> Confirguration Error, check information for objectref=dev0 and groupid=7
29/06/2017 19:51:27 ==> FunctionGetConfigurationStatus:Unhandled exception --Internal exception : , Exception Message: Organization cannot be null or empty.
Parameter name: Organization Name
29/06/2017 19:53:02 ==> Function: GetConfigurationStatus : Unhandled exception--Internal exception : , Exception Message: Organization cannot be null or empty.
Parameter name: Organization Name
29/06/2017 20:07:56 ==> Function: GetConfigurationStatus : Unhandled exception--Internal exception : , Exception Message: Organization cannot be null or empty.
Parameter name: Organization Name
11/07/2017 18:44:26 ==> Function: DYConfig-GetConfigurationStatus : Unhandled exception--Internal exception : , Exception Message: Organization cannot be null or empty.
Parameter name: Organization Name
11/07/2017 18:47:21 ==> Function: DYConfig-GetConfigurationStatus : Unhandled exception--Internal exception : , Exception Message: Organization cannot be null or empty.
Parameter name: Organization Name
11/07/2017 19:10:21 ==> Function: DYConfig-GetConfigurationStatus : Your request isn't authorized!--Internal exception : , Exception Message: Invalid JSON primitive: ȝ.
11/07/2017 19:11:14 ==> Function: DYConfig-GetConfigurationStatus : Your request isn't authorized!--Internal exception : , Exception Message: Invalid JSON primitive: ȝ.
11/07/2017 19:27:08 ==> Function: DYConfig-GetConfigurationStatus : Your request isn't authorized!--Internal exception : , Exception Message: Invalid JSON primitive: ȝ.
12/07/2017 23:15:01 ==> Function: DYLead-GetSearchedLeads : Unhandled exception--Internal exception : , Exception Message: Organization cannot be null or empty.
Parameter name: Organization Name
12/07/2017 23:15:38 ==> Function: DYLead-GetSearchedLeads : Unhandled exception--Internal exception : , Exception Message: Object reference not set to an instance of an object.
12/07/2017 23:16:49 ==> Function: DYLead-GetSearchedLeads : Unhandled exception--Internal exception : , Exception Message: Object reference not set to an instance of an object.
12/07/2017 23:17:13 ==> Function: DYLead-GetSearchedLeads : Unhandled exception--Internal exception : , Exception Message: Object reference not set to an instance of an object.
12/07/2017 23:18:45 ==> Function: DYLead-GetSearchedLeads : Unhandled exception--Internal exception : , Exception Message: Object reference not set to an instance of an object.
14/07/2017 14:56:33 ==> Function: DyAccount-GetConfigurationStatus : Unhandled exception--Internal exception : , Exception Message: Organization cannot be null or empty.
Parameter name: Organization Name
14/07/2017 14:58:03 ==> Function: DyAccount-GetConfigurationStatus : Unhandled exception--Internal exception : , Exception Message: Organization cannot be null or empty.
Parameter name: Organization Name
14/07/2017 15:01:42 ==> Internal Exception: Dynamics setup is incomplete or login credentials are not right. 
14/07/2017 15:03:18 ==> Internal Exception: Dynamics setup is incomplete or login credentials are not right. 
20/07/2017 00:40:03 ==> Your request isn't authorized!
20/07/2017 00:45:35 ==> No Chat in queue to publish
03/08/2017 19:49:25 ==> No Chat in queue to publish
03/08/2017 19:51:14 ==> No Chat in queue to publish
03/08/2017 20:35:43 ==> Function: DyLead-PostLead : Unhandled exception--Internal exception : , Exception Message: There is already an open DataReader associated with this Connection which must be closed first.
08/08/2017 18:36:01 ==> Function: SFChat-PostChat : Unhandled exception--Internal exception : , Exception Message: The entity with a name = 'new_websitealive' was not found in the MetadataCache.
08/08/2017 18:37:40 ==> Function: SFChat-PostChat : Unhandled exception--Internal exception : , Exception Message: The entity with a name = 'New_AliveChat' was not found in the MetadataCache.
08/08/2017 18:39:57 ==> Function: SFChat-PostChat : Unhandled exception--Internal exception : , Exception Message: 'new_alivechat' entity doesn't contain attribute with Name = 'new_websitealivechat'.
11/08/2017 16:36:50 ==> Function: DYConfig-GetConfigurationStatus : Unhandled exception--Internal exception : , Exception Message: Unable to connect to any of the specified MySQL hosts.
11/08/2017 16:43:53 ==> Function: DYConfig-GetConfigurationStatus : Unhandled exception--Internal exception : , Exception Message: Unable to connect to any of the specified MySQL hosts.
11/08/2017 16:52:29 ==> Function: DYConfig-GetConfigurationStatus : Unhandled exception--Internal exception : , Exception Message: Unable to connect to any of the specified MySQL hosts.
11/08/2017 16:55:03 ==> Function: DYConfig-GetConfigurationStatus : Unhandled exception--Internal exception : , Exception Message: Unable to connect to any of the specified MySQL hosts.
11/08/2017 17:02:10 ==> Function: DYConfig-GetConfigurationStatus : Unhandled exception--Internal exception : , Exception Message: Unable to connect to any of the specified MySQL hosts.
11/08/2017 17:03:49 ==> Function: DYConfig-GetConfigurationStatus : Unhandled exception--Internal exception : , Exception Message: Unable to connect to any of the specified MySQL hosts.
11/08/2017 22:41:25 ==> Function: DYConfig-GetConfigurationStatus : Unhandled exception--Internal exception : MySql.Data.MySqlClient.MySqlException (0x80004005): Access denied for user ''@'tcac-PC' (using password: NO)
   at MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   at MySql.Data.MySqlClient.Authentication.MySqlAuthenticationPlugin.ReadPacket(), Exception Message: Authentication to host '' for user '' using method 'mysql_native_password' failed with message: Access denied for user ''@'tcac-PC' (using password: NO)
11/08/2017 22:41:47 ==> Function: DYConfig-GetConfigurationStatus : Unhandled exception--Internal exception : MySql.Data.MySqlClient.MySqlException (0x80004005): Access denied for user ''@'tcac-PC' (using password: NO)
   at MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   at MySql.Data.MySqlClient.Authentication.MySqlAuthenticationPlugin.ReadPacket(), Exception Message: Authentication to host '' for user '' using method 'mysql_native_password' failed with message: Access denied for user ''@'tcac-PC' (using password: NO)
11/08/2017 22:46:42 ==> Confirguration Error - Managed solution Not Found, check information
14/08/2017 08:25:04 ==> Confirguration Error - Managed solution Not Found, check information
28/08/2017 10:34:41 ==> Function: DYAccount-GetSearchedAccounts : Unhandled exception--Internal exception : , Exception Message: Invalid URI: The format of the URI could not be determined.
28/08/2017 10:37:28 ==> No Chat in queue to publish
28/08/2017 10:40:12 ==> No Chat in queue to publish
28/08/2017 10:40:39 ==> No Chat in queue to publish
28/08/2017 10:49:32 ==> No Chat in queue to publish
